/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountProfile: typeof import('./components/button/AccountProfile.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppForm: typeof import('./components/forms/apps/AppForm.vue')['default']
    Banner: typeof import('./components/hero/Banner.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeNav: typeof import('./components/navigation/HomeNav.vue')['default']
    InspectionHeader: typeof import('./components/inspection/InspectionHeader.vue')['default']
    InspectionPagePlaceholder: typeof import('./components/inspection/InspectionPagePlaceholder.vue')['default']
    InspectionSidebar: typeof import('./components/inspection/InspectionSidebar.vue')['default']
    LanguageSwitcher: typeof import('./components/button/LanguageSwitcher.vue')['default']
    MenuCard: typeof import('./components/hero/MenuCard.vue')['default']
    NotificationButton: typeof import('./components/button/NotificationButton.vue')['default']
    NotificationDrawer: typeof import('./components/button/NotificationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./components/button/ThemeToggle.vue')['default']
  }
}
