/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/account/': RouteRecordInfo<'/account/', '/account', Record<never, never>, Record<never, never>>,
    '/account/profile': RouteRecordInfo<'/account/profile', '/account/profile', Record<never, never>, Record<never, never>>,
    '/account/security': RouteRecordInfo<'/account/security', '/account/security', Record<never, never>, Record<never, never>>,
    '/account/settings': RouteRecordInfo<'/account/settings', '/account/settings', Record<never, never>, Record<never, never>>,
    '/apps/': RouteRecordInfo<'/apps/', '/apps', Record<never, never>, Record<never, never>>,
    '/apps/form': RouteRecordInfo<'/apps/form', '/apps/form', Record<never, never>, Record<never, never>>,
    '/apps/point/': RouteRecordInfo<'/apps/point/', '/apps/point', Record<never, never>, Record<never, never>>,
    '/apps/point/form': RouteRecordInfo<'/apps/point/form', '/apps/point/form', Record<never, never>, Record<never, never>>,
    '/apps/service-tracking/': RouteRecordInfo<'/apps/service-tracking/', '/apps/service-tracking', Record<never, never>, Record<never, never>>,
    '/apps/service-tracking/form': RouteRecordInfo<'/apps/service-tracking/form', '/apps/service-tracking/form', Record<never, never>, Record<never, never>>,
    '/notification': RouteRecordInfo<'/notification', '/notification', Record<never, never>, Record<never, never>>,
    '/services/inspection/': RouteRecordInfo<'/services/inspection/', '/services/inspection', Record<never, never>, Record<never, never>>,
    '/services/inspection/form': RouteRecordInfo<'/services/inspection/form', '/services/inspection/form', Record<never, never>, Record<never, never>>,
  }
}
