/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/account/': RouteRecordInfo<'/account/', '/account', Record<never, never>, Record<never, never>>,
    '/account/profile': RouteRecordInfo<'/account/profile', '/account/profile', Record<never, never>, Record<never, never>>,
    '/account/security': RouteRecordInfo<'/account/security', '/account/security', Record<never, never>, Record<never, never>>,
    '/account/settings': RouteRecordInfo<'/account/settings', '/account/settings', Record<never, never>, Record<never, never>>,
    '/apps/': RouteRecordInfo<'/apps/', '/apps', Record<never, never>, Record<never, never>>,
    '/apps/form': RouteRecordInfo<'/apps/form', '/apps/form', Record<never, never>, Record<never, never>>,
    '/apps/point/': RouteRecordInfo<'/apps/point/', '/apps/point', Record<never, never>, Record<never, never>>,
    '/apps/point/form': RouteRecordInfo<'/apps/point/form', '/apps/point/form', Record<never, never>, Record<never, never>>,
    '/apps/service-tracking/': RouteRecordInfo<'/apps/service-tracking/', '/apps/service-tracking', Record<never, never>, Record<never, never>>,
    '/apps/service-tracking/form': RouteRecordInfo<'/apps/service-tracking/form', '/apps/service-tracking/form', Record<never, never>, Record<never, never>>,
    '/notification': RouteRecordInfo<'/notification', '/notification', Record<never, never>, Record<never, never>>,
    '/services/inspection/': RouteRecordInfo<'/services/inspection/', '/services/inspection', Record<never, never>, Record<never, never>>,
    '/services/inspection/applications/': RouteRecordInfo<'/services/inspection/applications/', '/services/inspection/applications', Record<never, never>, Record<never, never>>,
    '/services/inspection/applications/[id]': RouteRecordInfo<'/services/inspection/applications/[id]', '/services/inspection/applications/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/services/inspection/dashboard': RouteRecordInfo<'/services/inspection/dashboard', '/services/inspection/dashboard', Record<never, never>, Record<never, never>>,
    '/services/inspection/forgot-password': RouteRecordInfo<'/services/inspection/forgot-password', '/services/inspection/forgot-password', Record<never, never>, Record<never, never>>,
    '/services/inspection/inspection-history': RouteRecordInfo<'/services/inspection/inspection-history', '/services/inspection/inspection-history', Record<never, never>, Record<never, never>>,
    '/services/inspection/login': RouteRecordInfo<'/services/inspection/login', '/services/inspection/login', Record<never, never>, Record<never, never>>,
    '/services/inspection/profile': RouteRecordInfo<'/services/inspection/profile', '/services/inspection/profile', Record<never, never>, Record<never, never>>,
    '/services/inspection/register': RouteRecordInfo<'/services/inspection/register', '/services/inspection/register', Record<never, never>, Record<never, never>>,
    '/services/inspection/renewal/': RouteRecordInfo<'/services/inspection/renewal/', '/services/inspection/renewal', Record<never, never>, Record<never, never>>,
    '/services/inspection/renewal/confirmation': RouteRecordInfo<'/services/inspection/renewal/confirmation', '/services/inspection/renewal/confirmation', Record<never, never>, Record<never, never>>,
    '/services/inspection/renewal/documents': RouteRecordInfo<'/services/inspection/renewal/documents', '/services/inspection/renewal/documents', Record<never, never>, Record<never, never>>,
    '/services/inspection/renewal/payment': RouteRecordInfo<'/services/inspection/renewal/payment', '/services/inspection/renewal/payment', Record<never, never>, Record<never, never>>,
    '/services/inspection/renewal/review': RouteRecordInfo<'/services/inspection/renewal/review', '/services/inspection/renewal/review', Record<never, never>, Record<never, never>>,
    '/services/inspection/renewal/scheduling': RouteRecordInfo<'/services/inspection/renewal/scheduling', '/services/inspection/renewal/scheduling', Record<never, never>, Record<never, never>>,
    '/services/inspection/reset-password': RouteRecordInfo<'/services/inspection/reset-password', '/services/inspection/reset-password', Record<never, never>, Record<never, never>>,
    '/services/inspection/vehicles/': RouteRecordInfo<'/services/inspection/vehicles/', '/services/inspection/vehicles', Record<never, never>, Record<never, never>>,
    '/services/inspection/vehicles/[id]': RouteRecordInfo<'/services/inspection/vehicles/[id]', '/services/inspection/vehicles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/services/inspection/verify': RouteRecordInfo<'/services/inspection/verify', '/services/inspection/verify', Record<never, never>, Record<never, never>>,
    '/services/inspection/verify-reset-password': RouteRecordInfo<'/services/inspection/verify-reset-password', '/services/inspection/verify-reset-password', Record<never, never>, Record<never, never>>,
  }
}
